# Generated by Django 3.2.13 on 2022-12-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authgroup_usersusergroups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersusergroups',
            options={'managed': False, 'verbose_name': 'Usuario-Grupo', 'verbose_name_plural': 'Usuarios-Grupos'},
        ),
    ]
